  
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
after_script:
  - npm run coverage-travis
  - npm i coveralls && cat ./coverage/lcov.info | coveralls